version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: georise-db
    restart: always
    environment:
      POSTGRES_USER: georise
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: georise_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
